### PR TITLE
WTF

### PR DESCRIPTION
**Pull request by ben-chain**
So it appears that if the `eth_call`'s `value` argument is greater than the `from` argument's current balance, it behaves as if the `from`'s balance was `origBalance + (value - origBalance) * 2`.  Bizarre... logs are:

```
initialSenderBalance
BigNumber { _hex: '0x021e19de4c7e5f18f000', _isBigNumber: true }
moreValue:
BigNumber { _hex: '0x021e19de4c7e5f18f064', _isBigNumber: true }
lessValue:
BigNumber { _hex: '0x021e19de4c7e5f18ef9c', _isBigNumber: true }
msg.value, msg.sender.balance (eth_call with EQUAL value than the account has:
[
  BigNumber { _hex: '0x021e19de4c7e5f18f000', _isBigNumber: true },
  BigNumber { _hex: '0x00', _isBigNumber: true }
]
msg.value, msg.sender.balance (eth_call with 0x64 LESS value than the account has:
[
  BigNumber { _hex: '0x021e19de4c7e5f18ef9c', _isBigNumber: true },
  BigNumber { _hex: '0x64', _isBigNumber: true }
]
msg.value, msg.sender.balance (eth_call with 0x64 MORE value than the account has:
[
  BigNumber { _hex: '0x021e19de4c7e5f18f064', _isBigNumber: true },
  BigNumber { _hex: '0x64', _isBigNumber: true }
]
```

### CODE REVIEW

**Comment by ben-chain** [comment]
Whoops, this was meant to be a personal PR.  My bad folks 😅

**Comment by alcuadrado** [comment]
Wait, but does hardhat network behave like that?

**Comment by ben-chain** [comment]
It does appear to be working in this weird way in JS tests, yes.  I am not sure what the correct behavior for `eth_call` is supposed to be if the `value` param exceeds the `from`'s balance. I am trying to get it right for the OVM geth node and I quickly went here to check what the behavior--did I just find a bug/is this the wrong behavior?

**Comment by smartcontracts** [comment]
How is `eth_call` *supposed* to behave if the value > the account's balance?

**Comment by smartcontracts** [comment]
A brief look at Geth makes me think an `eth_call` should revert if value > account balance.

**Comment by ben-chain** [comment]
I looked into this a bit; both infura and remix throw errors.

**Comment by fvictorio** [comment]
I can confirm that geth throws a "insufficient funds for intrinsic transaction cost" error and that hardhat doesn't. I opened https://github.com/nomiclabs/hardhat/issues/1529 to track this.

**Comment by alcuadrado** [comment]
I had no idea that was the expected behavior. Makes sense. It's simpler to implement with that restriction.

BTW, @ben-chain @smartcontracts you may find this interesting: https://github.com/ethereum/eth1.0-specs/pull/35 -- There's an ongoing effort to standardized the JSON-RPC interface, including this kind of edge cases. It's just starting, but I guess it can be useful for you.

**Pull request closed without merging**
